import { NextRequest, NextResponse } from 'next/server';
import { OpenAI } from 'openai';

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: NextRequest) {
  try {
    const { occasion, recipientName, personalMessage, artStyle, hint, referenceImage } = await request.json();

    if (!occasion && !recipientName && !personalMessage) {
      return NextResponse.json(
        { success: false, error: 'Card details are required' },
        { status: 400 }
      );
    }

    console.log('🎨 [PROMPT API] Generating image prompt with OpenAI GPT-4...');

    // Call OpenAI to generate detailed DALL-E prompt (using GPT-4 like message API)
    const response = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: 'You are an expert at creating detailed, vivid image prompts for DALL-E. Generate highly descriptive prompts that specify visual elements, colors, mood, lighting, composition, and style.'
        },
        {
          role: 'user',
          content: `Create a detailed DALL-E image prompt for a ${occasion || 'greeting'} card for ${recipientName || 'someone special'}. 
          
Personal message context: "${personalMessage || 'No specific message provided'}"
Artistic Style: "${artStyle || 'any'}"
Additional Hint: "${hint || 'none'}"
${referenceImage ? `\nReference Image Provided: The user has uploaded an image. Analyze the content, style, and subject of the reference image and incorporate these elements into your generated prompt. The final image should be a new creation inspired by the reference.` : ''}

Requirements:
- Strictly adhere to the specified Artistic Style. If a style is given, it is mandatory.
- Incorporate the Additional Hint to guide the theme or subject matter.
- If a reference image is provided, ensure the prompt reflects its key characteristics.
- Be specific about visual elements (objects, people, scenery).
- Describe colors, lighting, and mood.
- Specify composition.
- Keep it under 100 words.
- Make it vivid and detailed.

Generate just the image prompt, nothing else.`
        }
      ],
      temperature: 0.8,
      max_tokens: 200,
    });

    const generatedPrompt = response.choices[0]?.message?.content?.trim();

    if (!generatedPrompt) {
      console.error('🎨 [PROMPT API] ❌ Empty response from OpenAI');
      throw new Error('No prompt generated by OpenAI');
    }

    console.log('🎨 [PROMPT API] ✅ Prompt generated successfully');

    return NextResponse.json({
      success: true,
      prompt: generatedPrompt,
    });

  } catch (error: any) {
    console.error('🎨 [PROMPT API] ❌ Error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Failed to generate prompt',
      },
      { status: 500 }
    );
  }
}
